import "@repo/ui/styles.css";
import "./globals.css";

import type { Metadata } from "next";
import { Geist, Inter } from "next/font/google";

import { cn } from "@/lib/utils";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cn("font-sans", inter.variable)}>
      <body className={geist.className + "text-foreground"}>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
