/* tslint:disable */
/* eslint-disable */
/**
 * Ant REST API
 * The REST API for Ant Habit Tracker.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CreateLogDto {
    'status': CreateLogDtoStatusEnum;
    'date': string;
    'note'?: string;
}

export const CreateLogDtoStatusEnum = {
    COMPLETED: 'completed',
    SKIPPED: 'skipped',
    MISSED: 'missed'
} as const;

export type CreateLogDtoStatusEnum = typeof CreateLogDtoStatusEnum[keyof typeof CreateLogDtoStatusEnum];


