/* tslint:disable */
/* eslint-disable */
/**
 * Ant REST API
 * The REST API for Ant Habit Tracker.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CreateHabitDto {
    'name': string;
    'description'?: string;
    'color': CreateHabitDtoColorEnum;
}

export const CreateHabitDtoColorEnum = {
    RED: 'red',
    ORANGE: 'orange',
    YELLOW: 'yellow',
    GREEN: 'green',
    MINT: 'mint',
    CYAN: 'cyan',
    BLUE: 'blue',
    INDIGO: 'indigo',
    PURPLE: 'purple',
    PINK: 'pink',
    BROWN: 'brown',
    GRAY: 'gray'
} as const;

export type CreateHabitDtoColorEnum = typeof CreateHabitDtoColorEnum[keyof typeof CreateHabitDtoColorEnum];


