/* tslint:disable */
/* eslint-disable */
/**
 * Ant REST API
 * The REST API for Ant Habit Tracker.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Log } from './log';
// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';

export interface Habit {
    'id': number;
    'name': string;
    'description': string;
    'icon': string;
    'color': HabitColorEnum;
    'isArchived': boolean;
    'user': User;
    'userId': number;
    'logs': Array<Log>;
    'createdAt': string;
    'updatedAt': string;
}

export const HabitColorEnum = {
    RED: 'red',
    ORANGE: 'orange',
    YELLOW: 'yellow',
    GREEN: 'green',
    MINT: 'mint',
    CYAN: 'cyan',
    BLUE: 'blue',
    INDIGO: 'indigo',
    PURPLE: 'purple',
    PINK: 'pink',
    BROWN: 'brown',
    GRAY: 'gray'
} as const;

export type HabitColorEnum = typeof HabitColorEnum[keyof typeof HabitColorEnum];


