/* tslint:disable */
/* eslint-disable */
/**
 * Ant REST API
 * The REST API for Ant Habit Tracker.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Habit } from './habit';

export interface Log {
    'id': number;
    'date': string;
    'createdDate': string;
    'status': LogStatusEnum;
    'note': string;
    'habitId': number;
    'habit': Habit;
}

export const LogStatusEnum = {
    COMPLETED: 'completed',
    SKIPPED: 'skipped',
    MISSED: 'missed'
} as const;

export type LogStatusEnum = typeof LogStatusEnum[keyof typeof LogStatusEnum];


