/* tslint:disable */
/* eslint-disable */
/**
 * Ant REST API
 * The REST API for Ant Habit Tracker.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UpdateLogDto {
    /**
     * Optional note or comment for the log entry.
     */
    'note'?: string;
    /**
     * Status of the log entry.
     */
    'status'?: UpdateLogDtoStatusEnum;
}

export const UpdateLogDtoStatusEnum = {
    COMPLETED: 'completed',
    SKIPPED: 'skipped',
    MISSED: 'missed'
} as const;

export type UpdateLogDtoStatusEnum = typeof UpdateLogDtoStatusEnum[keyof typeof UpdateLogDtoStatusEnum];


