/* tslint:disable */
/* eslint-disable */
/**
 * Ant REST API
 * The REST API for Ant Habit Tracker.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Habit } from './habit';

export interface User {
    'id': number;
    'username': string;
    'email': string;
    'password': string;
    'role': UserRoleEnum;
    'habits': Array<Habit>;
}

export const UserRoleEnum = {
    ADMIN: 'admin',
    BASIC: 'basic'
} as const;

export type UserRoleEnum = typeof UserRoleEnum[keyof typeof UserRoleEnum];


