/* tslint:disable */
/* eslint-disable */
/**
 * Ant REST API
 * The REST API for Ant Habit Tracker.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BadRequestResponseDto } from '../models';
// @ts-ignore
import type { CreateHabitDto } from '../models';
// @ts-ignore
import type { CreateLogDto } from '../models';
// @ts-ignore
import type { GetStatsResponseDto } from '../models';
// @ts-ignore
import type { Habit } from '../models';
// @ts-ignore
import type { HabitWithStreak } from '../models';
// @ts-ignore
import type { InternalServerErrorDto } from '../models';
// @ts-ignore
import type { Log } from '../models';
// @ts-ignore
import type { SignInDto } from '../models';
// @ts-ignore
import type { SignInResponseDto } from '../models';
// @ts-ignore
import type { SignUpDto } from '../models';
// @ts-ignore
import type { SignUpResponseDto } from '../models';
// @ts-ignore
import type { UpdateHabitDto } from '../models';
// @ts-ignore
import type { UpdateLogDto } from '../models';
// @ts-ignore
import type { UpdateUserDto } from '../models';
// @ts-ignore
import type { UpdateUserResponse } from '../models';
// @ts-ignore
import type { User } from '../models';
/**
 * Api - axios parameter creator
 */
export const ApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerGetHello: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 
         * @param {CreateHabitDto} createHabitDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createHabit: async (createHabitDto: CreateHabitDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createHabitDto' is not null or undefined
            assertParamExists('createHabit', 'createHabitDto', createHabitDto)
            const localVarPath = `/habits`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createHabitDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 
         * @param {number} habitId 
         * @param {CreateLogDto} createLogDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createLog: async (habitId: number, createLogDto: CreateLogDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'habitId' is not null or undefined
            assertParamExists('createLog', 'habitId', habitId)
            // verify required parameter 'createLogDto' is not null or undefined
            assertParamExists('createLog', 'createLogDto', createLogDto)
            const localVarPath = `/habits/{habitId}/logs`
                .replace(`{${"habitId"}}`, encodeURIComponent(String(habitId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createLogDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 
         * @param {number} id 
         * @param {UpdateUserDto} updateUserDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUser: async (id: number, updateUserDto: UpdateUserDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('createUser', 'id', id)
            // verify required parameter 'updateUserDto' is not null or undefined
            assertParamExists('createUser', 'updateUserDto', updateUserDto)
            const localVarPath = `/users/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateUserDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteHabit: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteHabit', 'id', id)
            const localVarPath = `/habits/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 
         * @param {number} habitId 
         * @param {number} logId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteLog: async (habitId: number, logId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'habitId' is not null or undefined
            assertParamExists('deleteLog', 'habitId', habitId)
            // verify required parameter 'logId' is not null or undefined
            assertParamExists('deleteLog', 'logId', logId)
            const localVarPath = `/habits/{habitId}/logs/{logId}`
                .replace(`{${"habitId"}}`, encodeURIComponent(String(habitId)))
                .replace(`{${"logId"}}`, encodeURIComponent(String(logId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUser: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteUser', 'id', id)
            const localVarPath = `/users/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHabit: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getHabit', 'id', id)
            const localVarPath = `/habits/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * The `currentDate` query parameter must be a **string representing the user\'s local date** in `YYYY-MM-DD` format.
         * @summary Retrieves statistics for a specific habit.
         * @param {number} id 
         * @param {string} currentDate The current date for which the streak should be calculated. Must be a string in &#x60;YYYY-MM-DD&#x60; format.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHabitStats: async (id: number, currentDate: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getHabitStats', 'id', id)
            // verify required parameter 'currentDate' is not null or undefined
            assertParamExists('getHabitStats', 'currentDate', currentDate)
            const localVarPath = `/habits/{id}/stats`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (currentDate !== undefined) {
                localVarQueryParameter['currentDate'] = currentDate;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHabits: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/habits`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * The date query parameters must be provided as **strings in the user\'s local date** using the `YYYY-MM-DD` format (ISO local date without time).
         * @summary Retrieves all habits along with their logs and current streak for a specific date range.
         * @param {string} startDate Start date of the requested range. Must be a string representing the user\&#39;s local date in &#x60;YYYY-MM-DD&#x60; format.
         * @param {string} endDate End date of the requested range. Must be a string representing the user\&#39;s local date in &#x60;YYYY-MM-DD&#x60; format.
         * @param {string} currentDate Current date in the user\&#39;s local timezone. Must be a string representing the user\&#39;s local date in &#x60;YYYY-MM-DD&#x60; format.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHabitsWithLogs: async (startDate: string, endDate: string, currentDate: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'startDate' is not null or undefined
            assertParamExists('getHabitsWithLogs', 'startDate', startDate)
            // verify required parameter 'endDate' is not null or undefined
            assertParamExists('getHabitsWithLogs', 'endDate', endDate)
            // verify required parameter 'currentDate' is not null or undefined
            assertParamExists('getHabitsWithLogs', 'currentDate', currentDate)
            const localVarPath = `/habits/logs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (startDate !== undefined) {
                localVarQueryParameter['startDate'] = startDate;
            }

            if (endDate !== undefined) {
                localVarQueryParameter['endDate'] = endDate;
            }

            if (currentDate !== undefined) {
                localVarQueryParameter['currentDate'] = currentDate;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 
         * @param {number} habitId 
         * @param {number} logId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLog: async (habitId: number, logId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'habitId' is not null or undefined
            assertParamExists('getLog', 'habitId', habitId)
            // verify required parameter 'logId' is not null or undefined
            assertParamExists('getLog', 'logId', logId)
            const localVarPath = `/habits/{habitId}/logs/{logId}`
                .replace(`{${"habitId"}}`, encodeURIComponent(String(habitId)))
                .replace(`{${"logId"}}`, encodeURIComponent(String(logId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Optionally filters logs using a date range. The `startDate` and `endDate` query parameters must be **strings representing the user\'s local date** in `YYYY-MM-DD` format.
         * @summary Retrieves logs for a specific habit.
         * @param {number} habitId 
         * @param {string} startDate Start date of the range filter. Must be a string in &#x60;YYYY-MM-DD&#x60; format.
         * @param {string} endDate End date of the range filter. Must be a string in &#x60;YYYY-MM-DD&#x60; format.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLogs: async (habitId: number, startDate: string, endDate: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'habitId' is not null or undefined
            assertParamExists('getLogs', 'habitId', habitId)
            // verify required parameter 'startDate' is not null or undefined
            assertParamExists('getLogs', 'startDate', startDate)
            // verify required parameter 'endDate' is not null or undefined
            assertParamExists('getLogs', 'endDate', endDate)
            const localVarPath = `/habits/{habitId}/logs`
                .replace(`{${"habitId"}}`, encodeURIComponent(String(habitId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (startDate !== undefined) {
                localVarQueryParameter['startDate'] = startDate;
            }

            if (endDate !== undefined) {
                localVarQueryParameter['endDate'] = endDate;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUser: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getUser', 'id', id)
            const localVarPath = `/users/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {object} [filter] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUsers: async (page?: number, limit?: number, filter?: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (filter !== undefined) {
                for (const [key, value] of Object.entries(filter)) {
                    localVarQueryParameter[key] = value;
                }
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 
         * @param {SignInDto} signInDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signIn: async (signInDto: SignInDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'signInDto' is not null or undefined
            assertParamExists('signIn', 'signInDto', signInDto)
            const localVarPath = `/auth/sign-in`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(signInDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 
         * @param {SignUpDto} signUpDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signUp: async (signUpDto: SignUpDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'signUpDto' is not null or undefined
            assertParamExists('signUp', 'signUpDto', signUpDto)
            const localVarPath = `/auth/sign-up`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(signUpDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 
         * @param {SignUpDto} signUpDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signUpAdmin: async (signUpDto: SignUpDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'signUpDto' is not null or undefined
            assertParamExists('signUpAdmin', 'signUpDto', signUpDto)
            const localVarPath = `/auth/sign-up/admin`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(signUpDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 
         * @param {string} id 
         * @param {UpdateHabitDto} updateHabitDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateHabit: async (id: string, updateHabitDto: UpdateHabitDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateHabit', 'id', id)
            // verify required parameter 'updateHabitDto' is not null or undefined
            assertParamExists('updateHabit', 'updateHabitDto', updateHabitDto)
            const localVarPath = `/habits/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateHabitDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 
         * @param {number} habitId 
         * @param {number} logId 
         * @param {UpdateLogDto} updateLogDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateLog: async (habitId: number, logId: number, updateLogDto: UpdateLogDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'habitId' is not null or undefined
            assertParamExists('updateLog', 'habitId', habitId)
            // verify required parameter 'logId' is not null or undefined
            assertParamExists('updateLog', 'logId', logId)
            // verify required parameter 'updateLogDto' is not null or undefined
            assertParamExists('updateLog', 'updateLogDto', updateLogDto)
            const localVarPath = `/habits/{habitId}/logs/{logId}`
                .replace(`{${"habitId"}}`, encodeURIComponent(String(habitId)))
                .replace(`{${"logId"}}`, encodeURIComponent(String(logId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateLogDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * Api - functional programming interface
 */
export const ApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async appControllerGetHello(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.appControllerGetHello(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['Api.appControllerGetHello']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 
         * @param {CreateHabitDto} createHabitDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createHabit(createHabitDto: CreateHabitDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Habit>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createHabit(createHabitDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['Api.createHabit']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 
         * @param {number} habitId 
         * @param {CreateLogDto} createLogDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createLog(habitId: number, createLogDto: CreateLogDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Log>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createLog(habitId, createLogDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['Api.createLog']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 
         * @param {number} id 
         * @param {UpdateUserDto} updateUserDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createUser(id: number, updateUserDto: UpdateUserDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UpdateUserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createUser(id, updateUserDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['Api.createUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteHabit(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Habit>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteHabit(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['Api.deleteHabit']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 
         * @param {number} habitId 
         * @param {number} logId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteLog(habitId: number, logId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Log>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteLog(habitId, logId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['Api.deleteLog']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteUser(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteUser(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['Api.deleteUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHabit(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Habit>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHabit(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['Api.getHabit']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * The `currentDate` query parameter must be a **string representing the user\'s local date** in `YYYY-MM-DD` format.
         * @summary Retrieves statistics for a specific habit.
         * @param {number} id 
         * @param {string} currentDate The current date for which the streak should be calculated. Must be a string in &#x60;YYYY-MM-DD&#x60; format.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHabitStats(id: number, currentDate: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetStatsResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHabitStats(id, currentDate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['Api.getHabitStats']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHabits(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Habit>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHabits(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['Api.getHabits']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * The date query parameters must be provided as **strings in the user\'s local date** using the `YYYY-MM-DD` format (ISO local date without time).
         * @summary Retrieves all habits along with their logs and current streak for a specific date range.
         * @param {string} startDate Start date of the requested range. Must be a string representing the user\&#39;s local date in &#x60;YYYY-MM-DD&#x60; format.
         * @param {string} endDate End date of the requested range. Must be a string representing the user\&#39;s local date in &#x60;YYYY-MM-DD&#x60; format.
         * @param {string} currentDate Current date in the user\&#39;s local timezone. Must be a string representing the user\&#39;s local date in &#x60;YYYY-MM-DD&#x60; format.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHabitsWithLogs(startDate: string, endDate: string, currentDate: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<HabitWithStreak>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHabitsWithLogs(startDate, endDate, currentDate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['Api.getHabitsWithLogs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 
         * @param {number} habitId 
         * @param {number} logId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLog(habitId: number, logId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Log>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLog(habitId, logId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['Api.getLog']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Optionally filters logs using a date range. The `startDate` and `endDate` query parameters must be **strings representing the user\'s local date** in `YYYY-MM-DD` format.
         * @summary Retrieves logs for a specific habit.
         * @param {number} habitId 
         * @param {string} startDate Start date of the range filter. Must be a string in &#x60;YYYY-MM-DD&#x60; format.
         * @param {string} endDate End date of the range filter. Must be a string in &#x60;YYYY-MM-DD&#x60; format.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLogs(habitId: number, startDate: string, endDate: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Log>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLogs(habitId, startDate, endDate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['Api.getLogs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUser(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUser(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['Api.getUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {object} [filter] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUsers(page?: number, limit?: number, filter?: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUsers(page, limit, filter, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['Api.getUsers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 
         * @param {SignInDto} signInDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async signIn(signInDto: SignInDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SignInResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.signIn(signInDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['Api.signIn']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 
         * @param {SignUpDto} signUpDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async signUp(signUpDto: SignUpDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SignUpResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.signUp(signUpDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['Api.signUp']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 
         * @param {SignUpDto} signUpDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async signUpAdmin(signUpDto: SignUpDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SignUpResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.signUpAdmin(signUpDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['Api.signUpAdmin']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 
         * @param {string} id 
         * @param {UpdateHabitDto} updateHabitDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateHabit(id: string, updateHabitDto: UpdateHabitDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Habit>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateHabit(id, updateHabitDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['Api.updateHabit']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 
         * @param {number} habitId 
         * @param {number} logId 
         * @param {UpdateLogDto} updateLogDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateLog(habitId: number, logId: number, updateLogDto: UpdateLogDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Log>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateLog(habitId, logId, updateLogDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['Api.updateLog']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * Api - factory interface
 */
export const ApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerGetHello(options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.appControllerGetHello(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 
         * @param {ApiCreateHabitRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createHabit(requestParameters: ApiCreateHabitRequest, options?: RawAxiosRequestConfig): AxiosPromise<Habit> {
            return localVarFp.createHabit(requestParameters.createHabitDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 
         * @param {ApiCreateLogRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createLog(requestParameters: ApiCreateLogRequest, options?: RawAxiosRequestConfig): AxiosPromise<Log> {
            return localVarFp.createLog(requestParameters.habitId, requestParameters.createLogDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 
         * @param {ApiCreateUserRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUser(requestParameters: ApiCreateUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<UpdateUserResponse> {
            return localVarFp.createUser(requestParameters.id, requestParameters.updateUserDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 
         * @param {ApiDeleteHabitRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteHabit(requestParameters: ApiDeleteHabitRequest, options?: RawAxiosRequestConfig): AxiosPromise<Habit> {
            return localVarFp.deleteHabit(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 
         * @param {ApiDeleteLogRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteLog(requestParameters: ApiDeleteLogRequest, options?: RawAxiosRequestConfig): AxiosPromise<Log> {
            return localVarFp.deleteLog(requestParameters.habitId, requestParameters.logId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 
         * @param {ApiDeleteUserRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUser(requestParameters: ApiDeleteUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<User> {
            return localVarFp.deleteUser(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 
         * @param {ApiGetHabitRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHabit(requestParameters: ApiGetHabitRequest, options?: RawAxiosRequestConfig): AxiosPromise<Habit> {
            return localVarFp.getHabit(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * The `currentDate` query parameter must be a **string representing the user\'s local date** in `YYYY-MM-DD` format.
         * @summary Retrieves statistics for a specific habit.
         * @param {ApiGetHabitStatsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHabitStats(requestParameters: ApiGetHabitStatsRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetStatsResponseDto> {
            return localVarFp.getHabitStats(requestParameters.id, requestParameters.currentDate, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHabits(options?: RawAxiosRequestConfig): AxiosPromise<Array<Habit>> {
            return localVarFp.getHabits(options).then((request) => request(axios, basePath));
        },
        /**
         * The date query parameters must be provided as **strings in the user\'s local date** using the `YYYY-MM-DD` format (ISO local date without time).
         * @summary Retrieves all habits along with their logs and current streak for a specific date range.
         * @param {ApiGetHabitsWithLogsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHabitsWithLogs(requestParameters: ApiGetHabitsWithLogsRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<HabitWithStreak>> {
            return localVarFp.getHabitsWithLogs(requestParameters.startDate, requestParameters.endDate, requestParameters.currentDate, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 
         * @param {ApiGetLogRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLog(requestParameters: ApiGetLogRequest, options?: RawAxiosRequestConfig): AxiosPromise<Log> {
            return localVarFp.getLog(requestParameters.habitId, requestParameters.logId, options).then((request) => request(axios, basePath));
        },
        /**
         * Optionally filters logs using a date range. The `startDate` and `endDate` query parameters must be **strings representing the user\'s local date** in `YYYY-MM-DD` format.
         * @summary Retrieves logs for a specific habit.
         * @param {ApiGetLogsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLogs(requestParameters: ApiGetLogsRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<Log>> {
            return localVarFp.getLogs(requestParameters.habitId, requestParameters.startDate, requestParameters.endDate, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 
         * @param {ApiGetUserRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUser(requestParameters: ApiGetUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<User> {
            return localVarFp.getUser(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 
         * @param {ApiGetUsersRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUsers(requestParameters: ApiGetUsersRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.getUsers(requestParameters.page, requestParameters.limit, requestParameters.filter, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 
         * @param {ApiSignInRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signIn(requestParameters: ApiSignInRequest, options?: RawAxiosRequestConfig): AxiosPromise<SignInResponseDto> {
            return localVarFp.signIn(requestParameters.signInDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 
         * @param {ApiSignUpRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signUp(requestParameters: ApiSignUpRequest, options?: RawAxiosRequestConfig): AxiosPromise<SignUpResponseDto> {
            return localVarFp.signUp(requestParameters.signUpDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 
         * @param {ApiSignUpAdminRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signUpAdmin(requestParameters: ApiSignUpAdminRequest, options?: RawAxiosRequestConfig): AxiosPromise<SignUpResponseDto> {
            return localVarFp.signUpAdmin(requestParameters.signUpDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 
         * @param {ApiUpdateHabitRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateHabit(requestParameters: ApiUpdateHabitRequest, options?: RawAxiosRequestConfig): AxiosPromise<Habit> {
            return localVarFp.updateHabit(requestParameters.id, requestParameters.updateHabitDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 
         * @param {ApiUpdateLogRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateLog(requestParameters: ApiUpdateLogRequest, options?: RawAxiosRequestConfig): AxiosPromise<Log> {
            return localVarFp.updateLog(requestParameters.habitId, requestParameters.logId, requestParameters.updateLogDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createHabit operation in Api.
 */
export interface ApiCreateHabitRequest {
    readonly createHabitDto: CreateHabitDto
}

/**
 * Request parameters for createLog operation in Api.
 */
export interface ApiCreateLogRequest {
    readonly habitId: number

    readonly createLogDto: CreateLogDto
}

/**
 * Request parameters for createUser operation in Api.
 */
export interface ApiCreateUserRequest {
    readonly id: number

    readonly updateUserDto: UpdateUserDto
}

/**
 * Request parameters for deleteHabit operation in Api.
 */
export interface ApiDeleteHabitRequest {
    readonly id: string
}

/**
 * Request parameters for deleteLog operation in Api.
 */
export interface ApiDeleteLogRequest {
    readonly habitId: number

    readonly logId: number
}

/**
 * Request parameters for deleteUser operation in Api.
 */
export interface ApiDeleteUserRequest {
    readonly id: number
}

/**
 * Request parameters for getHabit operation in Api.
 */
export interface ApiGetHabitRequest {
    readonly id: string
}

/**
 * Request parameters for getHabitStats operation in Api.
 */
export interface ApiGetHabitStatsRequest {
    readonly id: number

    /**
     * The current date for which the streak should be calculated. Must be a string in &#x60;YYYY-MM-DD&#x60; format.
     */
    readonly currentDate: string
}

/**
 * Request parameters for getHabitsWithLogs operation in Api.
 */
export interface ApiGetHabitsWithLogsRequest {
    /**
     * Start date of the requested range. Must be a string representing the user\&#39;s local date in &#x60;YYYY-MM-DD&#x60; format.
     */
    readonly startDate: string

    /**
     * End date of the requested range. Must be a string representing the user\&#39;s local date in &#x60;YYYY-MM-DD&#x60; format.
     */
    readonly endDate: string

    /**
     * Current date in the user\&#39;s local timezone. Must be a string representing the user\&#39;s local date in &#x60;YYYY-MM-DD&#x60; format.
     */
    readonly currentDate: string
}

/**
 * Request parameters for getLog operation in Api.
 */
export interface ApiGetLogRequest {
    readonly habitId: number

    readonly logId: number
}

/**
 * Request parameters for getLogs operation in Api.
 */
export interface ApiGetLogsRequest {
    readonly habitId: number

    /**
     * Start date of the range filter. Must be a string in &#x60;YYYY-MM-DD&#x60; format.
     */
    readonly startDate: string

    /**
     * End date of the range filter. Must be a string in &#x60;YYYY-MM-DD&#x60; format.
     */
    readonly endDate: string
}

/**
 * Request parameters for getUser operation in Api.
 */
export interface ApiGetUserRequest {
    readonly id: string
}

/**
 * Request parameters for getUsers operation in Api.
 */
export interface ApiGetUsersRequest {
    readonly page?: number

    readonly limit?: number

    readonly filter?: object
}

/**
 * Request parameters for signIn operation in Api.
 */
export interface ApiSignInRequest {
    readonly signInDto: SignInDto
}

/**
 * Request parameters for signUp operation in Api.
 */
export interface ApiSignUpRequest {
    readonly signUpDto: SignUpDto
}

/**
 * Request parameters for signUpAdmin operation in Api.
 */
export interface ApiSignUpAdminRequest {
    readonly signUpDto: SignUpDto
}

/**
 * Request parameters for updateHabit operation in Api.
 */
export interface ApiUpdateHabitRequest {
    readonly id: string

    readonly updateHabitDto: UpdateHabitDto
}

/**
 * Request parameters for updateLog operation in Api.
 */
export interface ApiUpdateLogRequest {
    readonly habitId: number

    readonly logId: number

    readonly updateLogDto: UpdateLogDto
}

/**
 * Api - object-oriented interface
 */
export class Api extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public appControllerGetHello(options?: RawAxiosRequestConfig) {
        return ApiFp(this.configuration).appControllerGetHello(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 
     * @param {ApiCreateHabitRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createHabit(requestParameters: ApiCreateHabitRequest, options?: RawAxiosRequestConfig) {
        return ApiFp(this.configuration).createHabit(requestParameters.createHabitDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 
     * @param {ApiCreateLogRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createLog(requestParameters: ApiCreateLogRequest, options?: RawAxiosRequestConfig) {
        return ApiFp(this.configuration).createLog(requestParameters.habitId, requestParameters.createLogDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 
     * @param {ApiCreateUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createUser(requestParameters: ApiCreateUserRequest, options?: RawAxiosRequestConfig) {
        return ApiFp(this.configuration).createUser(requestParameters.id, requestParameters.updateUserDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 
     * @param {ApiDeleteHabitRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteHabit(requestParameters: ApiDeleteHabitRequest, options?: RawAxiosRequestConfig) {
        return ApiFp(this.configuration).deleteHabit(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 
     * @param {ApiDeleteLogRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteLog(requestParameters: ApiDeleteLogRequest, options?: RawAxiosRequestConfig) {
        return ApiFp(this.configuration).deleteLog(requestParameters.habitId, requestParameters.logId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 
     * @param {ApiDeleteUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteUser(requestParameters: ApiDeleteUserRequest, options?: RawAxiosRequestConfig) {
        return ApiFp(this.configuration).deleteUser(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 
     * @param {ApiGetHabitRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getHabit(requestParameters: ApiGetHabitRequest, options?: RawAxiosRequestConfig) {
        return ApiFp(this.configuration).getHabit(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * The `currentDate` query parameter must be a **string representing the user\'s local date** in `YYYY-MM-DD` format.
     * @summary Retrieves statistics for a specific habit.
     * @param {ApiGetHabitStatsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getHabitStats(requestParameters: ApiGetHabitStatsRequest, options?: RawAxiosRequestConfig) {
        return ApiFp(this.configuration).getHabitStats(requestParameters.id, requestParameters.currentDate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getHabits(options?: RawAxiosRequestConfig) {
        return ApiFp(this.configuration).getHabits(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * The date query parameters must be provided as **strings in the user\'s local date** using the `YYYY-MM-DD` format (ISO local date without time).
     * @summary Retrieves all habits along with their logs and current streak for a specific date range.
     * @param {ApiGetHabitsWithLogsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getHabitsWithLogs(requestParameters: ApiGetHabitsWithLogsRequest, options?: RawAxiosRequestConfig) {
        return ApiFp(this.configuration).getHabitsWithLogs(requestParameters.startDate, requestParameters.endDate, requestParameters.currentDate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 
     * @param {ApiGetLogRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getLog(requestParameters: ApiGetLogRequest, options?: RawAxiosRequestConfig) {
        return ApiFp(this.configuration).getLog(requestParameters.habitId, requestParameters.logId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Optionally filters logs using a date range. The `startDate` and `endDate` query parameters must be **strings representing the user\'s local date** in `YYYY-MM-DD` format.
     * @summary Retrieves logs for a specific habit.
     * @param {ApiGetLogsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getLogs(requestParameters: ApiGetLogsRequest, options?: RawAxiosRequestConfig) {
        return ApiFp(this.configuration).getLogs(requestParameters.habitId, requestParameters.startDate, requestParameters.endDate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 
     * @param {ApiGetUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getUser(requestParameters: ApiGetUserRequest, options?: RawAxiosRequestConfig) {
        return ApiFp(this.configuration).getUser(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 
     * @param {ApiGetUsersRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getUsers(requestParameters: ApiGetUsersRequest = {}, options?: RawAxiosRequestConfig) {
        return ApiFp(this.configuration).getUsers(requestParameters.page, requestParameters.limit, requestParameters.filter, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 
     * @param {ApiSignInRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public signIn(requestParameters: ApiSignInRequest, options?: RawAxiosRequestConfig) {
        return ApiFp(this.configuration).signIn(requestParameters.signInDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 
     * @param {ApiSignUpRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public signUp(requestParameters: ApiSignUpRequest, options?: RawAxiosRequestConfig) {
        return ApiFp(this.configuration).signUp(requestParameters.signUpDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 
     * @param {ApiSignUpAdminRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public signUpAdmin(requestParameters: ApiSignUpAdminRequest, options?: RawAxiosRequestConfig) {
        return ApiFp(this.configuration).signUpAdmin(requestParameters.signUpDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 
     * @param {ApiUpdateHabitRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateHabit(requestParameters: ApiUpdateHabitRequest, options?: RawAxiosRequestConfig) {
        return ApiFp(this.configuration).updateHabit(requestParameters.id, requestParameters.updateHabitDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 
     * @param {ApiUpdateLogRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateLog(requestParameters: ApiUpdateLogRequest, options?: RawAxiosRequestConfig) {
        return ApiFp(this.configuration).updateLog(requestParameters.habitId, requestParameters.logId, requestParameters.updateLogDto, options).then((request) => request(this.axios, this.basePath));
    }
}

