name: Format Check

on:
  push:
  pull_request:

jobs:
  format-check:
    name: Run Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci
        env:
          HUSKY: 0

      - name: Check code formatting with Prettier
        run: npx prettier --check .
