name: Test

on:
  push:
  pull_request:

jobs:
  test-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run test

  test-api:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: 'development'
      JWT_SECRET: '123'
      CREATE_ADMIN_PASSWORD: 123
    defaults:
      run:
        working-directory: apps/api
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run test
      - run: npm run test:e2e